import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms & Conditions · EXPLAIN THIS REPO",
  description: "Acceptable use and disclaimers for Explain This Repo.",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[var(--color-background)]">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 py-16 sm:py-24">
        <h1 className="font-[family-name:var(--font-display)] font-black text-4xl sm:text-5xl uppercase tracking-tight mb-8">
          TERMS &amp; CONDITIONS
        </h1>

        <div className="space-y-8 font-[family-name:var(--font-body)] text-base leading-relaxed opacity-80">
          <section>
            <h2 className="font-[family-name:var(--font-display)] font-black text-xl uppercase tracking-tight mb-3">
              ACCEPTABLE USE
            </h2>
            <p>
              This tool is for personal, non-commercial use. Do not use it to scrape, mass-analyze,
              or redistribute repository data at scale. Do not attempt to bypass rate limits,
              abuse the GitHub API through this service, or use it to circumvent any access controls.
            </p>
          </section>

          <section>
            <h2 className="font-[family-name:var(--font-display)] font-black text-xl uppercase tracking-tight mb-3">
              LLM OUTPUT DISCLAIMER
            </h2>
            <p>
              The onboarding documents generated by this tool are produced by an AI model and may
              contain inaccuracies, omissions, or outdated information. The output is not a
              substitute for reading the actual source code. Always verify critical information
              against the repository itself.
            </p>
          </section>

          <section>
            <h2 className="font-[family-name:var(--font-display)] font-black text-xl uppercase tracking-tight mb-3">
              API COSTS
            </h2>
            <p>
              You supply your own Anthropic API key. You are solely responsible for any charges
              incurred from Anthropic as a result of using this tool. This application does not
              charge you any fees.
            </p>
          </section>

          <section>
            <h2 className="font-[family-name:var(--font-display)] font-black text-xl uppercase tracking-tight mb-3">
              LIMITATION OF LIABILITY
            </h2>
            <p>
              This tool is provided as-is, with no warranties. We are not responsible for any
              decisions made based on AI-generated content, nor for any API charges incurred
              through use of the service.
            </p>
          </section>

          <section>
            <h2 className="font-[family-name:var(--font-display)] font-black text-xl uppercase tracking-tight mb-3">
              CONTACT
            </h2>
            <p>
              Questions about these terms? Email us at{" "}
              <a
                href="mailto:codanzaprivatelimited@gmail.com"
                className="underline underline-offset-2 font-bold hover:text-[var(--color-accent)]"
              >
                codanzaprivatelimited@gmail.com
              </a>
              .
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
